name: Build, lint, test and deploy

on: [push]

jobs:
  test:
    name: Build, lint, test and deploy
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Install
        run: yarn install --immutable

      - name: Turbo build, lint, test
        run: yarn deploy --cache-dir=".turbo"
        env:
          TURBO_TOKEN: ${{ secrets.TURBO_TOKEN }}
          TURBO_TEAM: ${{ secrets.TURBO_TEAM }}