name: CI
on:
  push:
    branches:
      - main
      - beta
      - next
jobs:
  test:
    name: Build, lint, and test on Node
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/alvarlagerlof/action-node-yarn-chromium:latest 
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Install
        run: yarn install

      - name: Lint
        working-directory: ./core
        run: yarn lint

      - name: Link
        working-directory: ./core
        run: yarn link

      - name: Link to test
        working-directory: ./example
        run: yarn link next-banner

      - name: Build
        working-directory: ./core
        run: yarn build

      - name: Test
        working-directory: ./core
        run: yarn test

  publish:
    name: "Publish Module to NPM"
    needs: test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: 14
          registry-url: https://registry.npmjs.org/

      - name: Install deps
        uses: bahmutov/npm-install@v1

      - name: Build
        working-directory: ./core
        run: yarn build

      - name: Copy files for publishing
        run: |
          cp README.md ./core
          cp LICENSE ./core

      - name: Release
        working-directory: ./core
        run: npx semantic-release@17
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}
          GH_TOKEN: ${{secrets.GH_TOKEN}}
