name: CI
on:
  push:
    branches:
      - main
      - beta
      - next
jobs:
  test:
    name: Build, lint, and test on Node ${{ matrix.node }}
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Use Node ${{ matrix.node }}
        uses: actions/setup-node@v2
        with:
          node-version: 14

      - name: Install deps and build (with cache)
        uses: bahmutov/npm-install@v1

      - name: Lint
        working-directory: ./core
        run: yarn lint

      # Currently not working in CI
      # - name: Test
      #   run: |
      #     cd ./core
      #     yarn test

  publish:
    name: "Publish Module to NPM"
    needs: test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: 14
          registry-url: https://registry.npmjs.org/

      - name: Install deps
        uses: bahmutov/npm-install@v1

      - name: Build
        working-directory: ./core
        run: yarn build

      - name: Copy files for publishing
        run: |
          cp README.md ./core
          cp LICENSE ./core

      - name: Release
        working-directory: ./core
        run: npx semantic-release@17
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}
          GH_TOKEN: ${{secrets.GH_TOKEN}}
