name: Publish

on:
  push:
    branches:
      - main
      - next
      - beta
  workflow_run:
    workflows: ["Test"]
    branches: [main]
    types:
      - completed

jobs:
  publish:
    name: "Publish Module to NPM"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 14
          registry-url: https://registry.npmjs.org/

      - name: Install deps
        uses: bahmutov/npm-install@v1

      - name: Build
        working-directory: ./core
        run: yarn build

      - name: Copy files for publishing
        run: |
          cp README.md ./core
          cp LICENSE ./core

      - name: Release
        working-directory: ./core
        run: npx semantic-release@17
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}
          GH_TOKEN: ${{secrets.GH_TOKEN}}
